### PR TITLE
Fixed modal window closing #4

### LINKED ISSUE #4: Implement closing of modal window on click on backdrop

### PR DESCRIPTION
**Pull request by shelchkov**
Closes #4

### CODE REVIEW

File: assets/js/main.js [hunk 1]
```diff
@@ -150,7 +150,7 @@ function showInfo(user) {
 	infoBlock.innerHTML = userInfo;
 
 	document.querySelector("p#closeWindow").onclick = function() {
-		infoBlock.style.zIndex = "-1";
+		// infoBlock.style.zIndex = "-1";
```
Comment (shelchkov) [inline assets/js/main.js]: Remove comment.

File: index.html [hunk 2]
```diff
@@ -24,6 +24,7 @@ <h1>Загрузка</h1>
 		</div>
 	</div>
 	<div class="wrapper">
+		<p id="closeWindow" class="modal--backdrop"></p>
```
Comment (shelchkov) [inline index.html]: Should be a div.
