### PR TITLE
Fixed user cards #23

### LINKED ISSUE #23: Add id or unique class on every user
To understand what user was clicked.

### PR DESCRIPTION
**Pull request by shelchkov**
Closes #23

### CODE REVIEW

File: assets/js/main.js [hunk 1]
```diff
@@ -75,15 +84,10 @@ function updateContent() {
...
-	var userDivs = document.querySelectorAll(".user");
-	for(var i = 0; i < userDivs.length; i++) {
-		userDivs[i].onclick = function(event) {
-			const wrapper = document.querySelector(".wrapper");
-			wrapper.setAttribute("visibility", "visible");
-			document.querySelector(".info").setAttribute("visibility", "visible");
-			wrapper.style.zIndex = "1";
-			wrapper.style.opacity = 1;
-			clickHandler(event);
+	var userCards = document.querySelectorAll(".user");
```
Comment (shelchkov) [inline assets/js/main.js]: Use let instead of var
